#!/bin/bash
# Bake worker/renderer/setup.png into a C header (src/setup_png.h) so the
# firmware can display the device-setup screen with no network dependency.
#
# Re-run this whenever setup.png changes. The output is committed to git so
# the build doesn't depend on bake having been run.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SETUP_PNG="${SCRIPT_DIR}/../../worker/renderer/setup.png"
OUT_HEADER="${SCRIPT_DIR}/../src/setup_png.h"

if [ ! -f "$SETUP_PNG" ]; then
    echo "ERROR: setup PNG not found at $SETUP_PNG"
    echo "Run 'npm run preview:setup' in worker/renderer first."
    exit 1
fi

PNG_SIZE=$(stat -f%z "$SETUP_PNG")

{
    echo "// Auto-generated by scripts/bake-setup.sh from worker/renderer/setup.png."
    echo "// Do not edit by hand — re-run the script if the setup screen changes."
    echo "#pragma once"
    echo "#include <stdint.h>"
    echo
    xxd -i -n setup_png "$SETUP_PNG" \
        | sed -e 's/unsigned char/const uint8_t/' \
              -e 's/unsigned int/const uint32_t/'
} > "$OUT_HEADER"

echo "Wrote $OUT_HEADER (source PNG: ${PNG_SIZE} bytes)"
