#!/bin/bash
# Bake worker/renderer/menu.png into a C header (src/menu_png.h) so the firmware
# can render the on-device menu with no network dependency.
#
# Regenerate the PNG first: `npm run preview:menu` in worker/renderer.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
MENU_PNG="${SCRIPT_DIR}/../../worker/renderer/menu.png"
OUT_HEADER="${SCRIPT_DIR}/../src/menu_png.h"

if [ ! -f "$MENU_PNG" ]; then
    echo "ERROR: menu PNG not found at $MENU_PNG" >&2
    echo "Run 'npm run preview:menu' in worker/renderer first." >&2
    exit 1
fi

PNG_SIZE=$(stat -f%z "$MENU_PNG")

{
    echo "// Auto-generated by scripts/bake-menu.sh from worker/renderer/menu.png."
    echo "// Do not edit by hand — re-run the script if the menu changes."
    echo "#pragma once"
    echo "#include <stdint.h>"
    echo
    xxd -i -n menu_png "$MENU_PNG" \
        | sed -e 's/unsigned char/const uint8_t/' \
              -e 's/unsigned int/const uint32_t/'
} > "$OUT_HEADER"

echo "Wrote $OUT_HEADER (source PNG: ${PNG_SIZE} bytes)"
