#!/bin/bash
# Bake worker/renderer/splash.png into a C header (src/splash_png.h) so the
# firmware can display the splash screen with no network dependency.
#
# Re-run this whenever splash.png changes. The output is committed to git so
# the build doesn't depend on bake having been run.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SPLASH_PNG="${SCRIPT_DIR}/../../worker/renderer/splash.png"
OUT_HEADER="${SCRIPT_DIR}/../src/splash_png.h"

if [ ! -f "$SPLASH_PNG" ]; then
    echo "ERROR: splash PNG not found at $SPLASH_PNG"
    echo "Run 'npm run preview:splash' in worker/renderer first."
    exit 1
fi

PNG_SIZE=$(stat -f%z "$SPLASH_PNG")

{
    echo "// Auto-generated by scripts/bake-splash.sh from worker/renderer/splash.png."
    echo "// Do not edit by hand — re-run the script if the splash changes."
    echo "#pragma once"
    echo "#include <stdint.h>"
    echo
    xxd -i -n splash_png "$SPLASH_PNG" \
        | sed -e 's/unsigned char/const uint8_t/' \
              -e 's/unsigned int/const uint32_t/'
} > "$OUT_HEADER"

echo "Wrote $OUT_HEADER (source PNG: ${PNG_SIZE} bytes)"
